---
title: Engineering Mechanics - Statics
author: Arjun Jayaprakash
date: '2019-09-05'
slug: statics
categories:
  - Structures
  - Seismic Design and Analysis
tags:
  - Learning
---

Statics deals with the equilibrium of bodies, that is, those that are either at rest or move with a constant velocity. The most effective way of learning the principles of engineering mechanics is to solve as many problems as you can. Here is a generic suggestive list of the steps you take to solve problems in mechanics (Adapted from _Engineering mechanics, 14th edition, Hibbeler_). 

* Read the problem carefully and try to correlate the actual physical situation with the theory studied.
* Tabulate the problem data and draw to a large scale any necessary diagrams.
* Apply the relevant principles, generally in mathematical form. When writing any equations, be sure they are dimensionally homogeneous.
* Solve the necessary equations, and report the answer with no more than three significant figures.
* Study the answer with technical judgment and common sense to determine whether or not it seems reasonable.

## Lecture Notes

Click to view my [lecture notes](\files\CE214_Lecture_notes.pdf). These will be updated as I progress. 

## Video Tutorials

The following are some additional video tutorials I recorded for students in my statics class. The emphaasis of these videos are on solving problems as opposed to teaching concepts. 


### Force Vectors

<iframe width="560" height="315" src="https://www.youtube.com/embed/17Vin6hIMfQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 3D Vectors

<iframe width="560" height="315" src="https://www.youtube.com/embed/FdP7jWAa9FE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

