---
title: "Publications"
output: html_document
---

## Conference Papers

* **Jayaprakash, A.**, Nau, J., Pour-Ghaz, M., and Kowalsky, M., "Structural Consequences of Grout Deterioration in the Grouted Shear Stud Connection". _Bridge Engineering Institute_. 2019 ([PDF available](\Publications\Submission139.pdf))

* **Jayaprakash, A.**, and Kowalsky, M., "Balance Ratio to Characterize Earthquake Loading History for Performance Based Design". _12th Canadian Conference on Earthquake Engineering_. 2019 ([PDF available](\Publications\12CCEE.pdf))

## Technical Reports

* **Jayaprakash, A.**, Nau, J.M., Pour-Ghaz, M., Kowalsky, M.J., "Durability of the Grouted Shear Stud Connection at Low Temperatures". 4000(162), AKDOT Report, May 2019. ([PDF available](http://www.dot.state.ak.us/stwddes/research/assets/pdf/4000-162opt.pdf))

* **Jayaprakash, A.**, Price, C., Jiang, A., Pour-Ghaz, M., Nau, J., and Kowalsky, M., "Comparison of Cylinder and Cube Strength for Typical Grouts". _Constructed Facilities Laboratory, Dept. of Civil, Construction and Environmental Engineering, NC State University_. Summary Report RD-18-01. ([PDF available](\Publications\Cube_strength_test_report.pdf))