---
title: Sensitivity of NLTH Analysis of MDOF Bridges to Choice of Viscous Damping Models
author: Arjun Jayaprakash
date: '2017-04-27'
slug: sensitivity-of-nlth-analysis-of-mdof-bridges-to-choice-of-viscous-damping-models
categories:
  - Seismic Design and Analysis
tags:
  - Non linear Analysis
  - Viscous Damping Models
---

## Introduction

There has been a rising interest among engineers to conduct non-linear time history (NLTH) analysis as part
of the seismic design procedure for bridges. A good understanding of member parameters such as strength,
stiffness and damping are crucial for accurate results from NLTH analysis. Strength and stiffness in dynamic
analyses are well understood but the viscous damping model that is mostly being used in commercial analysis
programs, namely initial stiffness proportional Rayleigh damping, is questionable. This model prescribes a constant
damping matrix proportional to the initial stiffness matrix of a structure. Theoretically, this is inaccurate
because of three main reasons.

* Elastic viscous damping that accounts for material damping in the elastic range is not required to continue
the same function in the inelastic range where hysteretic damping exists.

* Since the stiffness of the system changes in the inelastic range, an argument can be made against the use
of a constant damping proportional to initial stiffness.

* Elastic viscous damping also accounts for energy dissipation by the foundation (mainly in bridges). Since
the demand going into the foundation remains constant after yielding, using the same damping in the
inelastic range is erroneous.

Albeit, the above can be stated in theory, if the sensitivity of response prediction to the variation in damping
models is minor, the simplest model would serve the purpose. Sensitivity of displacement predictions of SDOF
systems to choice of initial stiffness and tangent stiffness proportional damping models in NLTH analysis have
been studied in the past. It was found that the results vary considerably, with the tangent stiffness
proportional model better representing actual tests. This project makes an effort towards understanding the
sensitivity of response predictions of MDOF systems to the choice of four different damping models in NLTH
analysis.

## Research Report

For more details on this project, please read this [**report**](\files\Bridge_class_project.pdf).