---
title: "Balance Ratio to Characterize Earthquake Loading History - A pilot study"
author: Arjun Jayaprakash
date: '2020-01-30'
slug: balance-ratio-to-characterize-earthquake-loading-history-a-pilot-study
categories:
  - Projects
  - Structures
tags:
  - Seismic Design
  - Ground Motion Characterization
  - Statistical Approach
---

## Introduction

<div style="text-align: justify"> **Abstract:** Recent studies have revealed the impact of ground motion loading history on performance limit-states of RC bridge columns such as longitudinal reinforcement bar-buckling and residual drift ratio. Conventional hazard characterizations such as peak ground acceleration, spectral acceleration, and spectral displacement can only capture peak values of ground motion hazard and therefore fall short of providing the necessary information to account for these limit-states. In this study, a parameter termed as the opposite peak ratio is defined, explored, and shown to be useful in reproducing loading history characteristics of ground motions for displacement-based design. First, a study was designed to investigate correlations between the opposite peak ratio and the performance limit-states of reinforcement bar-buckling and residual drift ratio in RC bridge columns. By analyzing the results of non-linear time history analyses of numerical RC column models, it was established that these limit-states have a good correlation with the opposite peak ratio. Subsequently, a large number of past ground motions were analyzed and empirical models to estimate the opposite peak ratio were developed. These models can provide the mean and confidence intervals of the opposite peak ratio as a function of earthquake magnitude, epicentral distance, structural period, hysteretic model, and displacement ductility. They can be used in the displacement-based design process for reinforced concrete columns. </div>

*Paper under review...To be updated upon acceptance.* 