---
title: Seismic Design of Steel Bridge Piers with Socket Connection
author: Arjun Jayaprakash
date: '2020-02-24'
slug: seismic-design-of-steel-bridge-piers-with-socket-connection
categories: []
tags: []
---

## Poster Presentation Supplemental Materials

* [View Alternate Poster](\files\Poster_for_EERI_and_Graduate_Symposium_2020.pdf)
* [View Cheatsheet for simplified model](\files\Cheatsheet_for_GSS_Poster.pdf)
* [View Presentation](\files\Presentation_SEM_Symposium_2020.pdf)
* [View short write up on DDBD](\post\2020\03\01\an-inappropriately-short-summary-of-direct-displacement-based-design)


## Abstract

Direct displacement-based seismic design (DDBD) procedure demands that the designer be able to estimate the total displacement of a structural system at important limit states. Generally, this requirement is satisfied through simplified design equations that relate limit state strain or section curvature to global system displacement. In the case of steel bridge substructure systems with hollow circular columns and socket-type connections, estimation of limit state displacements is not trivial because of additional flexibility in the system, attributable to cap-beam flexure and socket connection rotation. However, there are no prior studies that have investigated these types of systems or provided any simplified design procedure. This study developed a set of simple relationships for estimating the displacement of these systems at column yield and local buckling limit states. First, large scale tests were performed on two-column bridge pier specimens. Fiber-based finite element models were subsequently developed to simulate the full cyclic behavior of steel bridge piers. Lastly, multiple parametric studies were performed using these fiber models to derive semi-empirical expressions that can estimate essential limit state displacements and the rate of strength degradation in these systems.


